export const actionTypes = {
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  CATEGORIES_IS_LOADING: "CATEGORIES_IS_LOADING",
  CATEGORIES_FETCH_DATA_SUCCESS: "CATEGORIES_FETCH_DATA_SUCCESS"
};